### ISSUE TITLE
Generic code for modules (e.g. over quotient rings)

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#1806]
Edit: I will briefly describe the purpose and challenge addressed here, reproducing what I learned from discussions with @jankoboehm. 

The code for the `ModuleFP`s is built up so that all higher routines from commutative and homological algebra can eventually be derived from a few basic routines. These may differ, depending on the "layer" (see below) on which they are implemented, but essentially they should boil down to the following three:
```julia
Base.in(a::FreeModElem{T}, M::SubModuleOfFreeModule{T}) where {T<:MyNewRingElem}
coordinates(v::FreeModElem{T}, M::SubModuleOfFreeModule{T}) where {T<:MyNewRingElem}
kernel(f::FreeModuleHom{DomainType, CodomainType}) where {
           DomainType<:FreeMod{<:MyNewRingElem},
           CodomainType<:FreeMod{<:MyNewRingElem}
          }
```
The above is a sample for the `SubModuleOfFreeModule`-layer: If one wants the `ModuleFP`-code to be running for some new, exotic type of rings with elements of type `MyNewRingElem`, one has to implement the above three methods and everything else should follow. Probably not in the most optimal way, but in that case: Just override the next method in question. 

Other layers are the `SubQuo`-layer, or, in case the new exotic ring is close to a polynomial ring, also a Groebner-basis layer. These have not been tried out yet -- at least not by me. 

In #1805 I implemented the above `SubModuleOfFreeModule`-layer over `MPolyQuo`s. Since the genericity of the code building on the above three routines has not yet been properly tested, we expect some hickups and uncertainties to pop up. This is to keep track of them and to help clarifying the precise methods to be implemented for the `SubModuleOfFreeModule`-layer. Updates on the status will be given over time below.

The first issue found is this one (run on #1805): 
```julia
R, (x, y, z) = polynomial_ring(QQ, ["x$i" for i in 1:3])

M = R[x y; y-1 z]
f = det(M)
I = ideal(R, f)
A, _ = quo(R, I)
A2 = FreeMod(A, 2) 
MA = change_base_ring(A, M)
phi = FreeModuleHom(A2, A2, MA)
K, inc = kernel(phi)
@test iszero(kernel(inc)[1])

psi = FreeModuleHom(A2, A2, ambient_representatives_generators(K))
K2, inc2 = kernel(psi)
@test iszero(kernel(inc2)[1])

phi2 = hom(A2, A2, ambient_representatives_generators(K2))

K3, inc3 = kernel(phi2)

K3 == K2
```

produces the complaint
```
ERROR: wrong rings
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] *(M::MonomialOrdering{FmpqMPolyRing}, N::Oscar.Orderings.ModuleOrdering{FreeMod{MPolyQuoElem{fmpq_mpoly}}})
   @ Oscar.Orderings ~/Oscar.jl/src/Rings/orderings.jl:1645
 [3] default_ordering(F::FreeMod{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:6174
 [4] default_ordering
   @ ~/Oscar.jl/src/Modules/UngradedModules.jl:1031 [inlined]
 [5] reduce(M::Oscar.SubModuleOfFreeModule{MPolyQuoElem{fmpq_mpoly}}, N::Oscar.SubModuleOfFreeModule{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:3832
 [6] ==(M::Oscar.SubModuleOfFreeModule{MPolyQuoElem{fmpq_mpoly}}, N::Oscar.SubModuleOfFreeModule{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:1264
 [7] compare_helper(M::SubQuo{MPolyQuoElem{fmpq_mpoly}}, N::SubQuo{MPolyQuoElem{fmpq_mpoly}}, comparer::typeof(==))
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:1823
 [8] ==(M::SubQuo{MPolyQuoElem{fmpq_mpoly}}, N::SubQuo{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:1896
 [9] top-level scope
   @ REPL[48]:1
```

**Comment by HechtiDerLachs** [comment]
Some time ago, I had asked for the morphisms of modules to also allow for base changes. That means whenever `f : M -> N` is a morphism of `R`-modules, then I want to also allow the case where `N` is really an `S`-module and I consider it as an `R`-module via some morphism `phi : R -> S`. This is similar to the mapping interface for polynomial rings, which allows a change of coefficient rings and the constructor for such homomorphisms was 
```julia
hom(M, N, v) # v is a Vector containing the images of the generators of M; this is the usual case
hom(M, N, v, phi) # Now we also pass on phi : R -> S with M an R-module and N an S-module.
```
In principal, this is up and running, i.e. it has been incorporated in the modules already. The issue I found now was that 
the `matrix` command does not take the possibility into account that we may have a base-change: 
```julia
R, (x,y) = QQ["x", "y"]
Q, phi = quo(R, ideal(R, x))
F = FreeMod(R, 1)
FF = FreeMod(Q, 1)
f = hom(F, FF, gens(FF), phi)
matrix(f)
```
produces
```
ERROR: MethodError: no method matching (::FmpqMPolyRing)(::MPolyQuoElem{fmpq_mpoly})
Closest candidates are:
  (::MPolyRing)(::RingElem, ::RingElem; check) at ~/Oscar.jl/src/Schemes/SpecOpen/Rings/Methods.jl:175
  (::FmpqMPolyRing)() at ~/.julia/packages/Nemo/5Z1ZH/src/flint/fmpq_mpoly.jl:1170
  (::AbstractAlgebra.Ring)(::Singular.n_RingElem{Singular.RingElemWrapper{S, T}}) where {S, T} at ~/.julia/packages/Singular/IjiQo/src/number/n_unknown.jl:379
  ...
Stacktrace:
 [1] setindex!(a::AbstractAlgebra.Generic.MatSpaceElem{fmpq_mpoly}, d::MPolyQuoElem{fmpq_mpoly}, r::Int64, c::Int64)
   @ AbstractAlgebra.Generic ~/.julia/packages/AbstractAlgebra/Oe2Uj/src/generic/Matrix.jl:62
 [2] matrix(a::FreeModuleHom{FreeMod{fmpq_mpoly}, FreeMod{MPolyQuoElem{fmpq_mpoly}}, MapFromFunc{FmpqMPolyRing, MPolyQuo{fmpq_mpoly}}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:751
 [3] top-level scope
   @ REPL[30]:1
```
Question: Shouldn't we make a dispatch for the case of a non-trivial base ring map? Alternatively, we could also restrict the `matrix` command to only accept morphisms over one and the same ring.

**Comment by HechtiDerLachs** [comment]
Composition of homomorphisms of modules also does not seem to work properly with base changes: 
```julia
R, (x,y) = QQ["x", "y"]
Q, phi = quo(R, ideal(R, x^2))
F = FreeMod(R, 1)
FQ = FreeMod(Q, 1)
f = hom(F, FQ, gens(FQ), phi)
W, (t,) = polynomial_ring(QQ, ["t"])
psi = hom(Q, W, [zero(W), W[1]])
FW = FreeMod(W, 1)
g = hom(FQ, FW, gens(FW), psi)
compose(f, g) 
```
throws the error
```julia
ERROR: Unable to coerce polynomial
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] (::FmpqMPolyRing)(a::fmpq_mpoly)
   @ Nemo ~/.julia/packages/Nemo/5Z1ZH/src/flint/fmpq_mpoly.jl:1204
 [3] FreeModuleHom(F::FreeMod{fmpq_mpoly}, G::FreeMod{fmpq_mpoly}, a::Vector{FreeModElem{fmpq_mpoly}}, h::FmpqMPolyRing)
   @ Oscar ~/Oscar.jl/src/Modules/ModuleTypes.jl:530
 [4] hom(F::FreeMod{fmpq_mpoly}, M::FreeMod{fmpq_mpoly}, V::Vector{FreeModElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:822
 [5] *(h::FreeModuleHom{FreeMod{fmpq_mpoly}, FreeMod{MPolyQuoElem{fmpq_mpoly}}, MapFromFunc{FmpqMPolyRing, MPolyQuo{fmpq_mpoly}}}, g::FreeModuleHom{FreeMod{MPolyQuoElem{fmpq_mpoly}}, FreeMod{fmpq_mpoly}, Oscar.MPolyAnyMap{MPolyQuo{fmpq_mpoly}, FmpqMPolyRing, Nothing, fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:4991
 [6] compose(h::FreeModuleHom{FreeMod{fmpq_mpoly}, FreeMod{MPolyQuoElem{fmpq_mpoly}}, MapFromFunc{FmpqMPolyRing, MPolyQuo{fmpq_mpoly}}}, g::FreeModuleHom{FreeMod{MPolyQuoElem{fmpq_mpoly}}, FreeMod{fmpq_mpoly}, Oscar.MPolyAnyMap{MPolyQuo{fmpq_mpoly}, FmpqMPolyRing, Nothing, fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:4994
 [7] top-level scope
   @ REPL[149]:1
```
The point is that the ring maps are not taken into account when setting up the new homomorphism. This must be taken care of.

**Comment by HechtiDerLachs** [comment]
There seems to be some exotic case which is not detected by the `hom`-method for modules. Try this:
```julia
R, (x,y,z) = QQ["x", "y", "z"]
A, _ = quo(R, ideal(R, [x^2, y, z]))
W, _ = localization(A, complement_of_ideal(ideal(R, [x,y,z])))
F = FreeMod(W, 2)
N, _ = quo(F, (ideal(W, [x,y,z])*F)[1])
H, interp = hom(N, F)
```
According to my manual computations, the hom-module `H` should be non-trivial with at least two different homomorphisms. But I get back a zero module. 

It might also be the case that the problem lays somewhere in the localizations, I don't know yet! In any case, I think the result returned is wrong.

**Comment by HechtiDerLachs** [comment]
I tried without the localization: 
```julia
R, (x,y,z) = QQ["x", "y", "z"]
A, _ = quo(R, ideal(R, [x^2, y, z]))
F = FreeMod(A, 2)
N, _ = quo(F, (ideal(A, [x,y,z])*F)[1])
H, interp = hom(N, F)
```
Surprisingly, this works.

**Comment by HechtiDerLachs** [comment]
> There seems to be some exotic case which is not detected by the `hom`-method for modules. Try this:

I tried again after restarting julia and now it works just fine. Before, I had been on another branch (#1818 ) and it seems that the changes I already made here resolve the problem. Hence, the broken test in #1818 should be resolved with a rebase on this branch. 

Edit: No! In the end, `iszero(H)` still returns `true`. So there is still a problem!

**Comment by HechtiDerLachs** [comment]
Internally, the generic code also uses `coordinates(a::FreeModElem, M::SubModuleOfFreeModule, task::Symbol)`. If the user does not implement this, they run into errors. Hence, the internal code should either restrict the use of these methods to polynomial rings or require the user to also implement this function.

**Comment by jankoboehm** [comment]
We had that in our list what has to be implemented, didn't we?

**Comment by HechtiDerLachs** [comment]
> We had that in our list what has to be implemented, didn't we?

Not with the signature including the `task`. Only the plain `coordinates(a::FreeModElem, M::SubModuleOfFreeModule)`.

**Comment by HechtiDerLachs** [comment]
> There seems to be some exotic case which is not detected by the `hom`-method for modules.

This should now also be fixed on #1805 .

Edit: Indeed it was due to a faulty implementation of the kernel method for free modules over `MPolyQuoLocalizedRing`s.

**Comment by HechtiDerLachs** [comment]
The `kernel` method does not seem to be implemented generically.
```julia
R, (x, y) = QQ["x", "y"]
I = ideal(R, x^2 + y^2)
A, p = quo(R, I)
F = FreeMod(A, 1)
M, pp = quo(F, [x*F[1]])
kernel(pp)
```
throws an error
```
ERROR: LoadError: wrong rings
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] *(M::MonomialOrdering{FmpqMPolyRing}, N::Oscar.Orderings.ModuleOrdering{FreeMod{MPolyQuoElem{fmpq_mpoly}}})
   @ Oscar.Orderings ~/Oscar.jl/src/Rings/orderings.jl:1645
 [3] default_ordering(F::FreeMod{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:6243
 [4] kernel(h::FreeModuleHom{FreeMod{MPolyQuoElem{fmpq_mpoly}}, SubQuo{MPolyQuoElem{fmpq_mpoly}}, Nothing})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:4090
 [5] top-level scope
   @ /tmp/bug.jl:6
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [7] top-level scope
   @ REPL[47]:1
in expression starting at /tmp/bug.jl:6
```

@jankoboehm : Should the user also implement a method for `kernel(F::FreeMod, M::SubQuo)`? Or should this run out of the box, once `kernel(F::FreeMod, G::FreeMod)` is implemented?

**Comment by HechtiDerLachs** [comment]
Free resolutions are also not yet functional: 
```julia
R, (x, y) = QQ["x", "y"]
I = ideal(R, x^2 + y^2)
A, p = quo(R, I)
F = FreeMod(A, 1)
M, pp = quo(F, [x*F[1]])
free_resolution(M)
```
also complains
```
RROR: wrong rings
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] *(M::MonomialOrdering{FmpqMPolyRing}, N::Oscar.Orderings.ModuleOrdering{FreeMod{MPolyQuoElem{fmpq_mpoly}}})
   @ Oscar.Orderings ~/Oscar.jl/src/Rings/orderings.jl:1645
 [3] default_ordering(F::FreeMod{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:6243
 [4] default_ordering(M::SubQuo{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:1677
 [5] free_resolution(M::SubQuo{MPolyQuoElem{fmpq_mpoly}})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules.jl:4591
 [6] top-level scope
   @ REPL[47]:1
```
-- which makes sense since there should be no `default_ordering` required.

**Comment by jankoboehm** [comment]
The task in coodinates gives the flexibility to choose between a plain lift or a liftstd. I would want to keep it in the signature. It can be just ignored where it is not applicable. However I do not know any situation we are thinking of where this question does not arise. For quotient rings or localizations it can just be passed on to the polynomial realm. It will then also trigger there the caching of the transformation matrix if liftstd is computed.

**Comment by HechtiDerLachs** [comment]
Ok, that is true: Even over other rings, it might make sense to provide a keyword to proceed via some internally cached methods or via new, direct computation. 

With the implementation now the `task` is ignored for the time being. But that can, of course, be changed. 

Either way, I think this should be discussed in a list of things to be implemented for the `SubModuleOfFreeModule` layer, so it's good to have this explicitly mentioned here.

**Comment by HechtiDerLachs** [comment]
A quick summary of what is now running and what remains to be addressed after yesterday's merge:

- [x]  Comparison of `SubQuo`s via `==`: now running generically
 - [x] `matrix` for homomorphisms with base change: now running generically.
 - [ ] composition of morphisms with base change: now running; maybe not all cross-cases tested properly yet!
 - [x] exotic calls to `hom` (issue above): resolved as an actual bug of the localization code. The generic `hom`-code in the modules seems to be clean. 
 - [ ] `coordinates(v::FreeModElem{T}, M::SubModuleOfFreeModule{T}, task::Symbol='something') where {T<:MyRingElemType}`: It has to be decided whether or not it is part of the requirements for the `SubModuleOfFreeModule`-layer to implement the methods with this particular signature.
 - [ ] We have to clarify whether `coordinates` should return an `SRow` or a `Vector`. Personally, I am in favour of `Vector` since it is easier to handle (for instance, it knows its length) and comes with more compatibility. The function is user-facing and I am not sure we want them to handle `SRow`s. On the other hand, using `SRow`s might prevent severe memory issues; but do we have examples to support such claims? 
 - [ ] The method `kernel(f::FreeModuleHom{<:FreeMod, <:SubQuo})` seems to not be implemented with truely generic code. I had to manually override it for modules over `MPolyQuo`s; see the comments in the file there.
 - [ ] `free_resolution`: The previous implementation for modules over polynomial rings has been restricted in its signature to that specific case. The generic case has been replaced by an iterative kernel computation similar to `free_resolution_via_kernels`. It should be decided whether or not one wants to keep it that way (I think it makes sense, because over general rings one can probably not expect to have more efficient methods). The programmer should eventually be informed that they want to override this implementation for their modules if they have faster algorithms.
 - [ ] `free_module(R::Ring, n::Int)` does not create a `FreeMod` over `R` for a general ring `R`. It has to be decided whether the generic code for this is changed or whether the user must implement `free_module(R::MyRing, n::Int)` themself for their ring of interest.

**Comment by fingolfin** [comment]
@HechtiDerLachs what's the status of this? I tried several of the examples at the top which were said to produce errors and they now all seem to work.

This issue is both long, talking about many different things, and old (not modify for over two years). Perhaps it would be better to start fresh and open one or more new issues with the remaining points, and closing this one ?

**Comment by HechtiDerLachs** [comment]
I will clean this up and eventually open a new issue.

Edit: All the code snippets here (when brought to current syntax) work now. But I will go through the list in the end and provide an updated list of tasks to be addressed in the future.
