### ISSUE TITLE
could not initialize the perl interpreter -- julia 1.6.4 on macos

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#831]
Once again there seems to be some issues with subprocess handling (I have added some extra output here):
```
julia> using Oscar
polymake:  WARNING: Recompiling in /Users/lorenz/.julia/polymake_user/wrappers.0/build/Opt, please be patient...
Compilation failed No child processes -- -1 -- ; see the error log below

ninja: Entering directory `/Users/lorenz/.julia/polymake_user/wrappers.0/build/Opt'
[1/1] touch /Users/lorenz/.julia/polymake_user/wrappers.0/build/Opt/.apps.built
BEGIN failed--compilation aborted at -e line 9.
ERROR: InitError: Exception occured at Polymake side:
could not initialize the perl interpreter
```

This occurs when polymake needs to recompile some wrappers during startup and is caused by some change in subprocess / SIGCHLD handling between julia 1.6.3 and julia 1.6.4 (which I haven't found yet, maybe inside libuv). But the wrappers are compiled without any errors, only waitpid seems to fail with `No child processes` because the SIGCHLD signal got lost/ignored.

A second try at `using Oscar` should work fine.

Unfortunately this affects running the doctests in the CI. I am looking into this and will try to come up with something that works on both 1.6.3 and 1.6.4 ...

cc @lkastner @HereAround

**Comment by benlorenz** [comment]
Fixed with the new polymake_jll binary (v400.500.0+1): https://github.com/oscar-system/Oscar.jl/runs/4334688011?check_suite_focus=true
